site_name: Estrutura_de_Projetos
site_url: https://example.com/
nav:
  - Home: index.md
  - API: api.md
theme: material

repo_name: "Estrutura de Projetos"
repo_url: "https://github.com/EricPettersonL/Estrutura_de_Projeto"

plugins:
  - search
  - mermaid2
  - mkdocstrings:
      default_handler: python
